# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-eventtools
  version: "1.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-eventtools-${{ version }}.tar.gz
  sha256: f2b8d5278d2871e1c4e8ed77a91fee136c33dc2c4f7cff88b1a05e133415cbf4

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django >=1.8
    - python-dateutil >=2.1
    - six >=1.14.0

tests:
  - python:
      imports:
        - eventtools
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Recurring event tools for django
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/gregplaysguitar/django-eventtools

extra:
  recipe-maintainers:
    - rxm7706
